### ISSUE TITLE
Mint and burn are missing nonReentrant modifier

### ISSUE THREAD

**Issue by junomonster** [Steemhunt/dixel-v2-contract#11]
# Description

https://github.com/Steemhunt/dixel-v2-contract/blob/657250a219bbf63e27b970336045d48640151b6f/contracts/DixelClubV2NFT.sol#L119-L124

Line 119: Mint the NFT, and then call the `_safeMint` function.
Line 124: Increment the tokenId

https://github.com/Steemhunt/dixel-v2-contract/blob/657250a219bbf63e27b970336045d48640151b6f/contracts/lib/ERC721Initializable.sol#L250-L260

`_safeMint` calls `_checkOnERC721Received` which has a re-entrancy opportunity.

# Impact

When an attacker has an opportunity to re-enter the NFT contract, the attacker can emit the `Mint` events twice with the same tokenId, by following steps:

1. Attacker call  the mint with to as an attacker's contract address.
2. NFT contract calls `onERC721Received` function of the attacker's contract. (tokenID = X)
3. Attacker's contract calls burn with tokenID = X.
4. Attacker's contract calls the mint function again. (tokenID = X)
5. Since the incrementation of the tokenId executes after the `_safeMint` function returns, so attacker can mint twice with the same tokenId.

# Recommendation

Add a nonReentrant modifier on the Mint/Burn functions. (https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/security/ReentrancyGuard.sol)

cc/ @jinmo

**Comment by assafom** [comment]
The impact is wrong... There are other safeguards in place - the following line:
```
        assert(tokenId == _editionData.length - 1);
```
Will make sure that the user can not reenter into mint. So the user can't mint twice with same token id.

I looked at this earlier, seems to me that the user can not reenter mint/burn because of this line. So actually the code seems safe at the moment.

Adding reentrancy guard is good practice but it will also make the execution more expensive.

Another option to have more safeguards would be to **follow the Checks Effects Interactions pattern by moving the `safeMint` to be the last line in the mint function.**
This way, since it will be done after all state changes have already been applied, there will be no benefit to reentering the contract - it will just act as if the user executed another transaction.

**Comment by sebayaki** [comment]
Yeah also, ERC721  `_mint` function checks the token existence internally.

```solidity
function _mint(address to, uint256 tokenId) internal virtual {
        require(!_exists(tokenId), "ERC721: token already minted");
```

but @assafom is right. I agree that we better move `_safeMint` call to the end of the mothod.

Thanks for the feedback!

**Comment by junomonster** [comment]
> The impact is wrong... There are other safeguards in place - the following line:
> 
> ```
>         assert(tokenId == _editionData.length - 1);
> ```
> 
> Will make sure that the user can not reenter into mint. So the user can't mint twice with same token id.
> 
> I looked at this earlier, seems to me that the user can not reenter mint/burn because of this line. So actually the code seems safe at the moment.
> 
> Adding reentrancy guard is good practice but it will also make the execution more expensive.
> 
> Another option to have more safeguards would be to **follow the Checks Effects Interactions pattern by moving the `safeMint` to be the last line in the mint function.** This way, since it will be done after all state changes have already been applied, there will be no benefit to reentering the contract - it will just act as if the user executed another transaction.

Oh, we missed that part :p. Thanks for the better suggestion!

**Comment by assafom** [comment]
> Thanks for the better suggestion!

Thanks for the good vibes 🙂
