### ISSUE TITLE
Whiltelisting logic should be fixed. 

### ISSUE THREAD

**Issue by syl-doo2** [Steemhunt/dixel-v2-contract#9]
Ref. : https://medium.com/@ItsCuzzo/using-merkle-trees-for-nft-whitelists-523b58ada3f9 

Don't use for loop for whitelisting. 
It is not efficient, and when the number of whilelist increases, the for loop must be reverted.

**Comment by syl-doo2** [comment]
The answer is using merkletree for whiltelisting.

**Comment by assafom** [comment]
Yes, I agree that a merkle tree is the most efficient solution, but that's a relatively more complex implementation.

**Comment by syl-doo2** [comment]
Not that complex. Let me implement it in 20 minutes.

**Comment by Nipol** [comment]
Anyone can create a collection, so if Merkle data can be stored and served from somewhere, it seems a good option.
The key is where to put the off-chain data.

**Comment by syl-doo2** [comment]
MerkleRootHash can be a on-chain data.

**Comment by Nipol** [comment]
I mean, the branch data that makes up the rootHash. Normally, only root hash doesn't work.

**Comment by syl-doo2** [comment]
https://github.com/Steemhunt/dixel-v2-contract/pull/5/commits/cd118ecea25afebb16a3b72858af022b17380619

**Comment by syl-doo2** [comment]
컨트랙은 이거 쓰면 되고, 외부에서 MerkleHashRoot 만들어서 넣으면 됩니다. 저는 여기까지.......

**Comment by sebayaki** [comment]
Related to #2 #6 #8

Oh using Merkle Tree could be the most efficient way of checking whitelist!

However, we probably have to think about where to store actual address data because we want to give the owner a nice interface so they can 
1. Check all whitelisted addresses
2. Add / remove addresses from the list

We'd like to avoid maintaining an external db or indices, so I guess I'll have to think about it more tomorrow.

Thank you so much guys for all thoughts and feedbacks here.

**Comment by syl-doo2** [comment]
You don't have to store the white list. 
You don't have to maintain an external db or indices.

You can throw away the rest if you just get Merkle Root Hash.

**Comment by sebayaki** [comment]
> You don't have to store the white list. 
> 
> You don't have to maintain an external db or indices.
> 
> 
> 
> You can throw away the rest if you just get Merkle Root Hash.

Apart from verifying whether the address is in whitelist or not, can we restore the entire whitelist from Merkle root hash?

Because otherwise the owner would not be able to add or remove from the list it if they don't keep the whole list themselves.

Also, to verify if the whitelisted address already claimed the nft or not, each claim process need to save an extra claimedAddress data on the contract - isn't it?
